const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');

const html = fs.readFileSync(__dirname + '/index.html', 'utf8');
const script = html.match(/<script>([\s\S]*?)<\/script>/)[1];
const values = {team:'red',state:'1',x:'-0.6',y:'1.8',z:'0.55',speed:'6.5',angle:'52',yaw:'-90',diameter:'0.071',drag:'0.5',threshold:'0.30'};
const context2d = new Proxy({}, {get: () => () => {}});
const elements = Object.fromEntries(Object.entries(values).map(([id,value]) => [id,{value,addEventListener(){}}]));
for (const id of ['scene','side']) elements[id] = {clientWidth:600,clientHeight:400,width:0,height:0,getContext:()=>context2d,addEventListener(){}};
for (const id of ['result','balance','aim','play','reset','resetHive']) elements[id] = {innerHTML:'',addEventListener(){}};
const sandbox = {document:{getElementById:id=>elements[id]},window:{devicePixelRatio:1,addEventListener(){}},requestAnimationFrame(){},Math,console};
vm.createContext(sandbox);
vm.runInContext(script + ';globalThis.sim={cellGeometry,cellCollision,integrate,simulateInside,recordShot,stepHive,get hives(){return hives}};', sandbox);
const {cellGeometry,cellCollision,integrate,recordShot,stepHive} = sandbox.sim;
const hive = cellGeometry(-25.5*.0254/2,1,true);
const mean = points => ({x:points.reduce((n,p)=>n+p.x,0)/points.length,y:points.reduce((n,p)=>n+p.y,0)/points.length,z:points.reduce((n,p)=>n+p.z,0)/points.length});
const opening = mean(hive.aperture);
const apertureBottom=mean([hive.aperture[0],hive.aperture[1]]);
assert.ok(Math.abs(apertureBottom.y-.5096)<.03&&Math.abs(apertureBottom.z-1.3237)<.03,'the aperture must align with the official CAD bottom rim');
assert.ok(Math.abs(hive.aperture[3].y-.3054)<.03&&Math.abs(hive.aperture[3].z-1.6769)<.03,'the aperture must align with the official CAD apex');
const outward = {x:hive.x,y:hive.y,z:hive.z,t:0,vx:3*hive.normal.x,vy:3*hive.normal.y,vz:3*hive.normal.z};
const bouncedOut = sandbox.sim.simulateInside(outward,hive);
assert.ok(Math.hypot(bouncedOut.track[0].x-outward.x,bouncedOut.track[0].y-outward.y,bouncedOut.track[0].z-outward.z)<1e-8,'the interior trajectory must start at the actual aperture crossing without a position jump');
assert.equal(bouncedOut.escaped,true,'a ball leaving the opening after entry must be detected');
assert.equal(bouncedOut.retained,false,'an escaped ball cannot be scored');
for(const h of Object.values(sandbox.sim.hives)){
  assert.equal(h.balls.length,3,'the initial NECTAR balls must be physical bodies');
  assert.ok(h.balls.every(b=>Math.hypot(b.vu,b.vv,b.vd)<.1),'initial balls must settle under gravity');
}
const bottom = mean(hive.back);
const side = mean([hive.aperture[0],hive.aperture[1],hive.back[1],hive.back[0]]);
assert.equal(cellCollision(opening,[hive],.0355), null, 'opening must remain passable');
assert.equal(cellCollision(bottom,[hive],.0355).kind, '封闭背板');
assert.equal(cellCollision(side,[hive],.0355).kind, '侧面');
elements.x.value = String(side.x);
elements.y.value = String(side.y);
elements.z.value = String(side.z);
assert.equal(integrate().wall.kind, '侧面', 'a trajectory contacting a closed face must fail');
elements.x.value = '-0.6';
elements.y.value = '1.8';
elements.z.value = '0.55';
elements.aim.onclick();
assert.match(elements.result.innerHTML, /命中开口/, 'the solver must still find a valid unobstructed shot');
elements.x.value = '0.6';
elements.y.value = '-1.8';
elements.aim.onclick();
assert.equal(elements.team.value, 'blue', 'solver must use the closer HIVE');
assert.match(elements.result.innerHTML, /命中开口/);
const blue = sandbox.sim.hives.blue;
for (let i=0;i<4;i++) recordShot('blue','pollen');
assert.equal(blue.moving,true,'enough added ball mass must release the HIVE');
for (let i=0;i<1000&&blue.moving;i++) stepHive(blue,.01);
assert.equal(blue.moving,false);
assert.equal(blue.up,1,'the other CELL must face up after a tip');
assert.equal(blue.tips,1);
elements.aim.onclick();
assert.equal(elements.state.value,'1');
assert.doesNotMatch(elements.result.innerHTML,/命中开口/,'a shot from the back must not enter the tipped CELL');
elements.y.value = '1.8';
elements.aim.onclick();
assert.match(elements.result.innerHTML,/命中开口/,'solver must retarget the exposed face after tipping');
const api=sandbox.window.HiveControl;
const solution=api.solve({x:0.6,y:1.8,z:0.55,speed:6.5,ballType:'pollen'});
assert.equal(solution.status,'hit','control API must return a usable solution');
assert.equal(solution.retained,true,'a successful shot must settle inside the CELL');
assert.equal(solution.dragCoefficient,.5,'the API must expose the assumed drag coefficient');
assert.equal(api.predict().status,'hit');
const firing=api.fire();
assert.equal(firing.shot.status,'hit');
assert.equal(firing.state.hives.blue.pollen,1);
vm.runInContext(fs.readFileSync(__dirname + '/cad/hive-mesh.js','utf8'), sandbox);
vm.runInContext('buildCadColliders();', sandbox);
const cadClearances=vm.runInContext('hives.red.balls.map(b=>{let p=storedBallWorld("red",b),out={};for(let k of ["rib","shell","back"]){let a=window.HIVE_CAD_MESH.red.plus[k],d=Infinity;for(let i=0;i<a.length;i+=9){let q=triangleDistance2(p,{x:a[i],y:a[i+1],z:a[i+2]},{x:a[i+3],y:a[i+4],z:a[i+5]},{x:a[i+6],y:a[i+7],z:a[i+8]});if(Number.isFinite(q))d=Math.min(d,q)}out[k]=Math.sqrt(d)}return {position:p,clearance:out}})',sandbox);
for(const {position,clearance} of cadClearances){
  assert.ok(position.y>.05&&position.y<.49&&position.z>1.2&&position.z<1.67,'an initial ball centre must be within the CAD CELL bounds');
  assert.ok(clearance.rib>.045&&clearance.shell>.045&&clearance.back>.045,'an initial NECTAR ball must clear the CAD rib, side and back skins');
}
const cadSolution=api.solve({x:-0.6,y:1.8,z:0.55,speed:6.5,ballType:'pollen'});
assert.equal(cadSolution.status,'hit','solver must find a path using CAD skin collision');
assert.ok(cadSolution.internalCollisions.every(c=>Number.isFinite(c.x)&&Number.isFinite(c.y)&&Number.isFinite(c.z)),'all contact points must be finite world coordinates');
const cadAfterTip=api.solve({x:0.6,y:1.8,z:0.55,speed:6.5,ballType:'pollen'});
assert.equal(cadAfterTip.status,'hit','CAD collision must follow the HIVE after tipping');
const cellOffsets=vm.runInContext(`['red','blue'].flatMap(name=>[1,-1].map(s=>{let a=window.HIVE_CAD_MESH[name][s>0?'plus':'minus'].rib,phi=(name==='red'?1:-1)*(hives[name].tips%2)*Math.PI/3,cy=0,cv=0,n=a.length/3;
  for(let i=0;i<a.length;i+=3){let y=a[i+1],v=a[i+2]-pivotZ;cy+=y*Math.cos(phi)+v*Math.sin(phi);cv+=v*Math.cos(phi)-y*Math.sin(phi)}
  let g=currentCellGeometry(name,s),p=g.aperture.concat(g.back);return Math.hypot(cy/n-p.reduce((q,c)=>q+c.y,0)/p.length,cv/n+pivotZ-p.reduce((q,c)=>q+c.z,0)/p.length)}))`,sandbox);
assert.equal(sandbox.sim.hives.blue.tips%2,1,'the geometry check must cover a tipped HIVE');
assert.ok(cellOffsets.every(d=>d<.03),'every proxy CELL, upward or downward, tipped or not, must coincide with the CAD CELL: '+cellOffsets.map(d=>d.toFixed(3)).join(', '));
console.log('HIVE collision checks passed');
